import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/sidebar/sidebar";
import { ShoppingProvider } from "./shopping/shoppingContext";
import NextTopLoader from "@/components/nextLoader/next-progress";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Free App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ShoppingProvider>
          <Sidebar />
          <NextTopLoader />
          {children}
        </ShoppingProvider>
      </body>
    </html>
  );
}
