"use client";
import Head from "next/head";
import Cart from "./cart";
import ProductList from "./productList";

const Shopping = () => {
  return (
    <div className="bg-white">
      <Head>
        <title>Shopping App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto p-6">
        <h1 className="text-4xl font-bold text-center mb-6">Shopping App</h1>
        <ProductList />
        <Cart />
      </main>
    </div>
  );
};

export default Shopping;
